"""Unified error codes for API responses."""

# Topic errors
TOPIC_CREATE_FAILED = "TOPIC_CREATE_FAILED"
TOPIC_NOT_FOUND = "TOPIC_NOT_FOUND"
TOPIC_ARCHIVE_FAILED = "TOPIC_ARCHIVE_FAILED"

# Node errors
NODE_NOT_FOUND = "NODE_NOT_FOUND"
NODE_EXPAND_FAILED = "NODE_EXPAND_FAILED"
NODE_GENERATION_FAILED = "NODE_GENERATION_FAILED"
GRAPH_UNAVAILABLE = "GRAPH_UNAVAILABLE"

# Graph errors
GRAPH_WRITE_FAILED = "GRAPH_WRITE_FAILED"

# Practice errors
PRACTICE_GENERATE_FAILED = "PRACTICE_GENERATE_FAILED"
PRACTICE_SUBMIT_FAILED = "PRACTICE_SUBMIT_FAILED"

# AI errors
AI_CALL_FAILED = "AI_CALL_FAILED"
AI_TIMEOUT = "AI_TIMEOUT"

# Config errors
INVALID_REQUEST = "INVALID_REQUEST"
CONFIG_SAVE_FAILED = "CONFIG_SAVE_FAILED"
SETTING_NOT_FOUND = "SETTING_NOT_FOUND"

# Review errors
REVIEW_GENERATE_FAILED = "REVIEW_GENERATE_FAILED"
REVIEW_SUBMIT_FAILED = "REVIEW_SUBMIT_FAILED"

# Export errors
EXPORT_FAILED = "EXPORT_FAILED"
